<a href="https://colab.research.google.com/github/fatimaabbasinaseer-png/main-python-task/blob/main/numpy_as_np.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

marks = [70,30,40,90,80]
print(marks)


[70, 30, 40, 90, 80]


In [ ]:
import numpy as np

marks =np.array([70,30,40,90,80])
print(marks + 5)

[75 35 45 95 85]


In [ ]:
import numpy as np
marks= np.array([[70,30,40,90,80],
                [40,50,30,70,90]])
print(marks)

[[70 30 40 90 80]
 [40 50 30 70 90]]


In [ ]:
import numpy as np

marks = np.array([[70,30,40,90,80],
                  [40,50,30,70,80],
                  [90,40,80,70,50]])
print(marks)
print("\nmarks + 5 =\n", marks + 5)
print("\nShape:", marks.shape)
print("Size:", marks.size)

[[70 30 40 90 80]
 [40 50 30 70 80]
 [90 40 80 70 50]]

marks + 5 =
 [[75 35 45 95 85]
 [45 55 35 75 85]
 [95 45 85 75 55]]

Shape: (3, 5)
Size: 15


In [ ]:
import numpy as np
marks = np.array([
    [70,30,40,90,80],
    [40,50,30,70,90],
    [90,40,80,70,50]])

print(marks.ndim)
print(marks.shape)
print(marks.size)
print(marks.dtype)

2
(3, 5)
15
int64


In [ ]:
import numpy as np
marks =np.array([70,30,40,90,80])

print(marks[0])
print(marks[-2])

70
90


In [ ]:
import numpy as np
marks = np.array([[70,30,40,90,80],[40,50,30,70,90]])

print(marks[0,2])
print(marks[1, - 2])

40
70


In [ ]:
import numpy as np
marks = np.array([70,30,40,90,80])
print(marks[1:4])

marks = np.array([
    [70,30,40,90,80],
    [40,50,30,70,90]
    ])
print(marks[1,1:4])

[30 40 90]
[50 30 70]


In [ ]:
import numpy as np
marks = np.array([70,30,40,90,80])
print(marks + 5)
print(marks * 5)
print(marks - 5)
print(marks / 5)


[75 35 45 95 85]
[350 150 200 450 400]
[65 25 35 85 75]
[14.  6.  8. 18. 16.]


In [ ]:
marks =np.array([70,30,40,90,80])
print(marks[2]+5)


45


In [ ]:
import numpy as np
std1_marks = np.array([70,30,40,90,80])
std2_marks = np.array([40,50,30,70,90])

print(std1_marks + std2_marks)
print(std1_marks - std2_marks)
print(std1_marks * std2_marks)
print(std1_marks / std2_marks)
print(std1_marks % std2_marks)

[110  80  70 160 170]
[ 30 -20  10  20 -10]
[2800 1500 1200 6300 7200]
[1.75       0.6        1.33333333 1.28571429 0.88888889]
[30 30 10 20 80]


In [ ]:
import numpy as np
std1_marks = np.array([70,30,40,90,80])
print(np.sqrt(std1_marks))
std2_marks = np.array([40,50,30,70,90])
print(np.power(std1_marks  ,2))
std3_marks = np.array([40,1,5,9,30,7,70,90,5])
print(np.round(std3_marks))


[8.36660027 5.47722558 6.32455532 9.48683298 8.94427191]
[4900  900 1600 8100 6400]
[40  1  5  9 30  7 70 90  5]


In [ ]:
marks = np.array([70,30,40,90,80])
print(marks >= 50)

[ True False False  True  True]


In [ ]:
import numpy as np
marks = np.array([70,30,40,90,80])
print(marks[marks <= 50])

[30 40]


In [ ]:
import pandas as pd
df = pd.read_csv("/content/socialmedia.csv")
print(df)

       Student_ID  Age  Gender Academic_Level Primary_Platform  \
0     STU_2024000   19  Female  Undergraduate         Snapchat   
1     STU_2024001   19  Female  Undergraduate        Instagram   
2     STU_2024002   17  Female    High School           TikTok   
3     STU_2024003   16  Female    High School          YouTube   
4     STU_2024004   17    Male    High School         LinkedIn   
...           ...  ...     ...            ...              ...   
4495  STU_2028495   16    Male    High School          YouTube   
4496  STU_2028496   19  Female  Undergraduate         LinkedIn   
4497  STU_2028497   19    Male  Undergraduate        Instagram   
4498  STU_2028498   16    Male    High School         LinkedIn   
4499  STU_2028499   24    Male  Undergraduate        Instagram   

      Daily_Usage_Hours  Weekend_Extra_Hours Device_Type  \
0                   7.5                  1.5  Smartphone   
1                   4.6                  1.3  Smartphone   
2                  10.9    